version: 0.1

phases:
pre_build:
  commands:
  - echo This is pre_build
build:
  commands:
  - echo Starting build `date`
  - mvn clean package
post_build:
  commands:
  - echo Build completed on `date`
artifacts: 
files:
- target/awselasticgitapp.war
discard-paths: true