# This file controls the AWS CodeBuild

version: 0.1
phases:
  build:
    commands:
      - echo Build started on `date`       
  post_build:
    commands:
      - echo Build completed on `date`      
artifacts:
  files:
    - target/awswebapp-0.0.1-SNAPSHOT.war
  discard-paths: yes