# This file controls the AWS CodeBuild

version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean install -f awselasticbeanstalk-example/pom.xml
  post_build:
    commands:
      - echo Build Package Start....
      - mvn package -f awselasticbeanstalk-example/
artifacts:
  files:
    - '**/awselasticgitapp.war'
  discard-paths: yes
  base-directory: 'awselasticbeanstalk-example'
